<?php

return [
    
  "SUCCESS_CODE" => '700',
  "REDIRECT_CODE" => '800',
  "ERROR_CODE" => '600',
  "USER_NOT_LOGGED_IN_CODE" => '601',
  "USER_NOT_AUTHORIZED_CODE" => '602',
  "FORCE_LOGOUT_CODE" => '603',
  "RELATION_PRESENT_CODE" => '604',
  "RESTRICTED_CONTENT" => '605',
  "CONTENT_NOT_FOUND" => '606',
  "GUEST_ID_MISSING" => '607',
  "DATA_ERROR_CODE" => '610',
  "MERGE_ACCOUNT_ERROR_CODE" => '612',
  "IGNORE_ERROR" => '615',
  "FORCE_MOBILE_VERIFICATION" => '621',
  "REQUEST_RECENCY_FAILED" => '617',
  "REQUEST_INTEGRITY_FAILED" => '618',
  "REQUEST_UNIQUENESS_FAILED" => '619',
  "REQUEST_LIMIT_EXCEEDED" => '620',
  "NON_LOGGEDIN_LOGIN_POPUP" => '625'

];
